
id: trusted-environment
file: TrustedEnvironment
term: 信頼された環境
description: >
  この仕様の目的上、信頼できる環境には次のものがあります。
     - 適切なアンチウィルス/マルウェア対策ソフトウェアをインストールした組織が所有するマシン
     - 暗号鍵の利用者が所有するマシン
     - 組織が[暗号鍵](#key)や[シード](#seed)の使用を許可する他のマシン

  組織の「信頼された環境」ポリシーでは、ハードディスクの暗号化、短い画面ロックのタイムアウト、十分に[エントロピー](#entropy)なアカウントのパスワード、その他の賢明なセキュリティ対策が必要です。

  さらに、信頼できる環境では、可能であれば物理的なアクセス制御を利用して、許可されていない個人によるキーボードや画面の「肩ごしののぞき見」を防止する必要があります。

  インターネットカフェ、図書館、その他の公共スペースなどの公共のマシンは、信頼された環境「ではありません」。